version: '3'
services:
  db:
    image: postgres:14.2
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 45s
      retries: 5
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    restart: always
  web:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    restart: on-failure
    image: notecards-web:1.0
    environment:
      - ALLOWED_HOSTS
      - CSRF_COOKIE_DOMAIN
      - CSRF_TRUSTED_ORIGINS
      - DATABASE_URL
      - DJANGO_DEBUG
      - DJANGO_ENV
      - PORT
      - SECRET_KEY
    depends_on:
      - db

volumes:
  pg_data:
