# Generated by Django 4.0.2 on 2022-02-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=200),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
