# Generated by Django 4.0.2 on 2022-02-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notecards", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notecard",
            old_name="description",
            new_name="content",
        ),
        migrations.AlterField(
            model_name="notecard",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
